CREATE TABLE Calls
(
	Id INT PRIMARY KEY IDENTITY,
	DateTime DATETIME2 NOT NULL,
	Phone NVARCHAR(15) NOT NULL,
	StartAddress NVARCHAR(80) NOT NULL,
	EndAddress NVARCHAR(80) NOT NULL,
	CarId INT
	FOREIGN KEY (CarId) REFERENCES dbo.Cars(Id),
	DispatcherId INT
);