CREATE TABLE Models
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(30) NOT NULL,
	Body NVARCHAR(30) NOT NULL,
	Fuel NVARCHAR(20) NOT NULL,
	HP INT NOT NULL,
	Price INT NOT NULL,
	BrandId INT  NOT NULL
	FOREIGN KEY (BrandId) REFERENCES dbo.Brands(Id)
);